{\rtf1\ansi\ansicpg1252\cocoartf2639
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 .AppleSystemUIFontMonospaced-Regular;}
{\colortbl;\red255\green255\blue255;\red27\green31\blue35;\red160\green169\blue180;}
{\*\expandedcolortbl;;\cssrgb\c14118\c16078\c18431;\cssrgb\c68627\c72157\c75686\c20000;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs49\fsmilli24650 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 personal_project: On-Campus-Navigation-System-for-Disabled-Student}