name: 
  -Jiaji Sun
personal_project: 
  -On-Campus-Navigation-System-for-Disabled-Student
ux-ui-criticism:
  -https://vimeo.com/756194873
models-from-data:
  -https://github.com/philipsun-cu/On-Campus-Navigation-System-for-Disabled-Student/blob/main/navi/navi/navi/ContentView.swift#L17
